[package]
name = "rsp-client-executor"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = ""

[lints]
workspace = true

[dependencies]
alloy-sol-types.workspace = true
itertools = "0.13.0"
serde.workspace = true
serde_json.workspace = true
serde_with = "3.12.0"
thiserror.workspace = true

# workspace
rsp-mpt.workspace = true
rsp-primitives.workspace = true

# reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-consensus-common.workspace = true
reth-errors.workspace = true
reth-ethereum-consensus.workspace = true
reth-ethereum-primitives = { workspace = true, features = ["serde-bincode-compat"] }
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-execution-types.workspace = true
reth-optimism-chainspec = { workspace = true, optional = true }
reth-optimism-consensus = { workspace = true, optional = true }
reth-optimism-evm = { workspace = true, optional = true }
reth-optimism-primitives = { workspace = true, optional = true, features = ["serde", "serde-bincode-compat"] }
reth-primitives-traits.workspace = true
reth-trie.workspace = true

# revm
revm.workspace = true
revm-primitives.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-evm.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true

# op
op-alloy-network = { workspace = true, optional = true }
op-alloy-rpc-types = { workspace = true, optional = true }

# weaver dependency
twine-constants.workspace = true
twine-l1-consensus-verifier-precompile.workspace = true
twine-l1-transactions-precompile = { workspace = true, optional = true, default-features = false }
twine-zstd-precompile.workspace = true

[features]
default = ["mainnet"]
optimism = [
  "dep:op-alloy-network",
  "dep:op-alloy-rpc-types",
  "dep:reth-optimism-evm",
  "dep:reth-optimism-consensus",
  "dep:reth-optimism-chainspec",
  "dep:reth-optimism-primitives",
  "rsp-primitives/optimism",
]
testnet = ["twine-l1-transactions-precompile/testnet"]
devnet = ["twine-l1-transactions-precompile/devnet"]
mainnet = ["twine-l1-transactions-precompile/mainnet"]
